### PR TITLE
[close #39] - Rename Falcon Motor Controllers to Talon Motor Controllers

### LINKED ISSUE #39: Rename Falcon Motor Controllers to Talon Motor Controllers
The falcon motorcontrollers should have been named the Talon motorcontrollers because the motorcontroller inside of the Falcon 500 is the TalonFX. However, we chose the name FalconMotorController because we already had a group of motorcontroller classes called TalonMotorController.

To fix this you need to

- [ ] Head over to the falcon directory in motorcontrol rename FalconVelocityController to TalonFXVelocity controller and FalconPositionController to TalonFXPositionController.
- [ ] Rename the directory to Talon
- [ ] You might be able to use the VSCode find and replace sidebar to help you do the majority of the work

### PR DESCRIPTION
**Pull request by bemoche**
### [close #39] - Rename Falcon Motor Controllers to Talon Motor Controllers
- [x] Rename FalconVelocityController to TalonFXVelocity controller and FalconPositionController to TalonFXPositionController.
- [x] Rename the directory to Talon.
- [x] Replace falon by TalonFX in relevant files.

### CODE REVIEW

**Comment by theVerySharpFlat** [comment]
Thanks for the PR! I'm just curious, how did you find this repository?

We're a high-schooler-run team and appreciate all of the help we can get!

**Comment by bemoche** [comment]
Happy to help !
I was just cruising the Explore section and your issue was on the first page.
I had nothing else to do, i guess, so why not ! 😂

**Review by bemoche — COMMENTED** [review]
👍

**Comment by theVerySharpFlat** [comment]
> Happy to help ! I was just cruising the Explore section and your issue was on the first page. I had nothing else to do, i guess, so why not ! 😂

Ah, that makes sense. I'm glad our paths crossed. Thanks for the help 😄

**Pull request merged**
